In [1]:
import tensorflow as tf

In [3]:
weights = tf.Variable(tf.truncated_normal([2,3]))
biases = tf.Variable(tf.truncated_normal([3]))

save_file = './weights.ckpt'

saver = tf.train.Saver()

with tf.Session() as session:
    saver.restore(session, save_file)
    print('weights : ')
    print(session.run(weights))
    print('biases : ')
    print(session.run(biases))

weights : 
[[ 0.3543286  -0.56371665  0.14997749]
 [-0.06521665  1.3028779   0.41212609]]
biases : 
[ 0.193979   -0.08566199 -0.09524798]
